### ISSUE TITLE
Prep database to take in image files, and create reference hashes

### ISSUE THREAD

**Issue by vas1295** [xlab-classes/cse442-spring2022-team-team-aether#24]
**Task Tests**

*Test 1*

1. Open the database. 
2. Ensure that the passwords are saved as a hash instead of text (i.e., the actual password).

*Test 2*

1. Open the database. 
2. Ensure that references to the images created by particular users are stored appropriately.

**Comment by seongjae20** [comment]
This task is delayed to sprint 3 because we do not have functionality meme part now. So, we do not need this now.
