### ISSUE TITLE
Standardize common variable names (Class Activity)

### ISSUE THREAD

**Issue by mskravec** [xlab-classes/cse442-spring2022-team-team-aether#27]
There is confusion with how certain variables are passed around between sections of the code. To make it more legible we should standardize common variable names such as "Username" and "Password"

**Comment by jbrown49** [comment]
**Task Tests**

*Test 1:*

1. Find any variables that fall under the same topics/concepts
2. Modify those variable names such that the topics/concepts and names are concattenated
