### ISSUE TITLE
Make username appear on the top left

### ISSUE THREAD

**Issue by susanbrethauer** [xlab-classes/cse442-spring2022-team-team-aether#37]
**Task Tests**

*Test 1*
1. Open webpage ( [here ](http://cheshire.cse.buffalo.edu:4639/index))
2. Log in
3. Navigate to the user page by clicking the "your account" button on the left
4. See that your username appears on the top left of the user's page when logged in

**Comment by seongjae20** [comment]
The 'Task Tests' is not bold because it has only 1 star before and after that.
