### ISSUE TITLE
Test the creation of memes

### ISSUE THREAD

**Issue by jbrown49** [xlab-classes/cse442-spring2022-team-team-aether#49]
**Task Tests**

*Test 1*

1. Push all working code to dev
2. Clone the latest version of dev
3. Start the python server
4. Open localhost and create an account
5. Go to make, select different templates, colors and strings
6. For each meme, hit the make button and download the meme
7. Confirm that it matches what the user wants

**Comment by seongjae20** [comment]
No labels.
